### ISSUE TITLE
wsdl2py — ValueError: Unicode strings with encoding declaration are not supported

### ISSUE THREAD

**Issue by RealJTG** [soapteam/soapfish#82]
```
> wsdl2py.exe -c http://services.rs.ge/WayBillService/WayBillService.asmx?WSDL
Traceback (most recent call last):
  File "D:\repo\rs.ge\venv\Scripts\wsdl2py-script.py", line 9, in <module>
    load_entry_point('soapfish==0.6dev', 'console_scripts', 'wsdl2py')()
  File "D:\repo\rs.ge\venv\lib\site-packages\soapfish\wsdl2py.py", line 112, in main
    code = generate_code_from_wsdl(xml, target, opt.use_wsa, cwd=cwd)
  File "D:\repo\rs.ge\venv\lib\site-packages\soapfish\wsdl2py.py", line 64, in generate_code_from_wsdl
    xmlelement = etree.fromstring(xml)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src\lxml\lxml.etree.c:70569)
  File "parser.pxi", line 1823, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:106368)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```
Can be fixed by adding `xml.encode(encoding)` at [wsdl2py.py#L64](https://github.com/FelixSchwarz/soapfish/blob/a9f6c4c721d0dd22aa35d42f046d225cb1bbabb8/soapfish/wsdl2py.py#L64) but I'm not quite sure what's actually happening there, because if you save file locally and run `wsdl2py.exe -c WayBillService.wsdl` it works fine.

Jinja2==2.8
MarkupSafe==0.23
argparse==1.4.0
lxml==3.4.4
pythonic-testcase==1.2.1
requests==2.9.1
six==1.10.0
soapfish==0.6dev

**Comment by pope1ni** [comment]
My apologies - this bug was actually introduced by 0fbd617 and the fix is to change [utils.py#L20](https://github.com/FelixSchwarz/soapfish/blob/0fbd617a14b656a2ca1e9580bc02e3bd50465894/soapfish/utils.py#L20) to use `.content` instead of `.text` so that we have the raw binary string to pass to the XML parser.

I already have this change and a number of other fixes queued up to submit, but it is taking me a while to finalise some of the bits and pieces I've been working on - hopefully I can finish things off this week.

**Comment by pope1ni** [comment]
I have been working on a lot of fixes and this one should be solved in my [improvements](https://github.com/flightdataservices/soapfish/tree/improvements) branch by the commit [45c2532](https://github.com/flightdataservices/soapfish/commit/45c2532). I still have a few more things to finish before I submit a pull request.

**Comment by FelixSchwarz** [comment]
I pulled the changes from @pope1ni and it works for me now.
